// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: myconfigmap.proto

package myconfigmap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyConfigMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// configmap uses struct tag: protobuf:"bytes,2,rep,name=data"`
	Data map[string]string `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MyConfigMap) Reset() {
	*x = MyConfigMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myconfigmap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyConfigMap) ProtoMessage() {}

func (x *MyConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_myconfigmap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyConfigMap.ProtoReflect.Descriptor instead.
func (*MyConfigMap) Descriptor() ([]byte, []int) {
	return file_myconfigmap_proto_rawDescGZIP(), []int{0}
}

func (x *MyConfigMap) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type MyConfigMap2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data map[string]string `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MyConfigMap2) Reset() {
	*x = MyConfigMap2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myconfigmap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyConfigMap2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyConfigMap2) ProtoMessage() {}

func (x *MyConfigMap2) ProtoReflect() protoreflect.Message {
	mi := &file_myconfigmap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyConfigMap2.ProtoReflect.Descriptor instead.
func (*MyConfigMap2) Descriptor() ([]byte, []int) {
	return file_myconfigmap_proto_rawDescGZIP(), []int{1}
}

func (x *MyConfigMap2) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type MyConfigMapSameEnumAs1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data map[string]string `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MyConfigMapSameEnumAs1) Reset() {
	*x = MyConfigMapSameEnumAs1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myconfigmap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyConfigMapSameEnumAs1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyConfigMapSameEnumAs1) ProtoMessage() {}

func (x *MyConfigMapSameEnumAs1) ProtoReflect() protoreflect.Message {
	mi := &file_myconfigmap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyConfigMapSameEnumAs1.ProtoReflect.Descriptor instead.
func (*MyConfigMapSameEnumAs1) Descriptor() ([]byte, []int) {
	return file_myconfigmap_proto_rawDescGZIP(), []int{2}
}

func (x *MyConfigMapSameEnumAs1) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type DataBinaryDataConfigMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data       map[string]string `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BinaryData map[string]string `protobuf:"bytes,3,rep,name=BinaryData,proto3" json:"BinaryData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DataBinaryDataConfigMap) Reset() {
	*x = DataBinaryDataConfigMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myconfigmap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBinaryDataConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBinaryDataConfigMap) ProtoMessage() {}

func (x *DataBinaryDataConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_myconfigmap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBinaryDataConfigMap.ProtoReflect.Descriptor instead.
func (*DataBinaryDataConfigMap) Descriptor() ([]byte, []int) {
	return file_myconfigmap_proto_rawDescGZIP(), []int{3}
}

func (x *DataBinaryDataConfigMap) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataBinaryDataConfigMap) GetBinaryData() map[string]string {
	if x != nil {
		return x.BinaryData
	}
	return nil
}

var File_myconfigmap_proto protoreflect.FileDescriptor

var file_myconfigmap_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x79, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x0b, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d,
	0x61, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x37,
	0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x74, 0x0a, 0x0c, 0x4d, 0x79, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x32, 0x12, 0x2b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x4d, 0x61, 0x70, 0x32, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x88, 0x01,
	0x0a, 0x16, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x53, 0x61, 0x6d,
	0x65, 0x45, 0x6e, 0x75, 0x6d, 0x41, 0x73, 0x31, 0x12, 0x35, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4d, 0x61, 0x70, 0x53, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x41, 0x73, 0x31, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x93, 0x02, 0x0a, 0x17, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4d, 0x61, 0x70, 0x12, 0x36, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44,
	0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x48, 0x0a, 0x0a,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0x3d, 0x0a, 0x0f, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x6d, 0x79, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x6d, 0x61, 0x70, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_myconfigmap_proto_rawDescOnce sync.Once
	file_myconfigmap_proto_rawDescData = file_myconfigmap_proto_rawDesc
)

func file_myconfigmap_proto_rawDescGZIP() []byte {
	file_myconfigmap_proto_rawDescOnce.Do(func() {
		file_myconfigmap_proto_rawDescData = protoimpl.X.CompressGZIP(file_myconfigmap_proto_rawDescData)
	})
	return file_myconfigmap_proto_rawDescData
}

var file_myconfigmap_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_myconfigmap_proto_goTypes = []interface{}{
	(*MyConfigMap)(nil),             // 0: MyConfigMap
	(*MyConfigMap2)(nil),            // 1: MyConfigMap2
	(*MyConfigMapSameEnumAs1)(nil),  // 2: MyConfigMapSameEnumAs1
	(*DataBinaryDataConfigMap)(nil), // 3: DataBinaryDataConfigMap
	nil,                             // 4: MyConfigMap.DataEntry
	nil,                             // 5: MyConfigMap2.DataEntry
	nil,                             // 6: MyConfigMapSameEnumAs1.DataEntry
	nil,                             // 7: DataBinaryDataConfigMap.DataEntry
	nil,                             // 8: DataBinaryDataConfigMap.BinaryDataEntry
}
var file_myconfigmap_proto_depIdxs = []int32{
	4, // 0: MyConfigMap.Data:type_name -> MyConfigMap.DataEntry
	5, // 1: MyConfigMap2.Data:type_name -> MyConfigMap2.DataEntry
	6, // 2: MyConfigMapSameEnumAs1.Data:type_name -> MyConfigMapSameEnumAs1.DataEntry
	7, // 3: DataBinaryDataConfigMap.Data:type_name -> DataBinaryDataConfigMap.DataEntry
	8, // 4: DataBinaryDataConfigMap.BinaryData:type_name -> DataBinaryDataConfigMap.BinaryDataEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_myconfigmap_proto_init() }
func file_myconfigmap_proto_init() {
	if File_myconfigmap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_myconfigmap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyConfigMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myconfigmap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyConfigMap2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myconfigmap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyConfigMapSameEnumAs1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myconfigmap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBinaryDataConfigMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_myconfigmap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_myconfigmap_proto_goTypes,
		DependencyIndexes: file_myconfigmap_proto_depIdxs,
		MessageInfos:      file_myconfigmap_proto_msgTypes,
	}.Build()
	File_myconfigmap_proto = out.File
	file_myconfigmap_proto_rawDesc = nil
	file_myconfigmap_proto_goTypes = nil
	file_myconfigmap_proto_depIdxs = nil
}
